# Generated by Django 3.1.2 on 2020-10-28 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='images/parking_ground/')),
            ],
            options={
                'verbose_name_plural': 'Parking Grounds',
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('fee', models.CharField(blank=True, max_length=500)),
                ('booked', models.BooleanField()),
                ('parking_ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingground')),
            ],
            options={
                'verbose_name_plural': 'Parking Slots',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=280)),
                ('car_model', models.CharField(max_length=300)),
                ('start_time', models.CharField(max_length=100, verbose_name='Starting Time')),
                ('end_time', models.CharField(max_length=100, verbose_name='Ending Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
