# Generated by Django 3.1.2 on 2020-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
