# Generated by Django 3.1.2 on 2020-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_booking_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_plate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
