# Generated by Django 3.1.2 on 2020-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
