# Generated by Django 3.1.2 on 2020-10-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20201028_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='period',
            field=models.CharField(blank=True, max_length=200, verbose_name='Booking Period'),
        ),
    ]
