# Generated by Django 3.1.2 on 2020-10-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_booking_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='period',
            field=models.TimeField(blank=True, max_length=200, verbose_name='Booking Period'),
        ),
    ]
