# Generated by Django 3.1.2 on 2020-10-31 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20201031_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='period',
            field=models.TimeField(default=datetime.time, verbose_name='Booking Period'),
        ),
    ]
