# Generated by Django 3.1.2 on 2020-10-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20201031_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='period',
        ),
    ]
