# Generated by Django 3.0.10 on 2020-11-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_remove_booking_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_on',
        ),
    ]
