# Generated by Django 3.1.2 on 2020-10-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_cahrged',
            new_name='charged_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transction_ref',
            new_name='transaction_ref',
        ),
    ]
