# Generated by Django 3.0.10 on 2020-11-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0003_auto_20201028_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_on',
            new_name='made_on',
        ),
    ]
